# API명세서 2번 쿼리
SELECT STATION_NM, SUM(PSSNGR_CNT) DIV 365 AS TOT_CNT FROM (
	SELECT STATION_NM, '1월'  AS MON_NM, JAN_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '2월' AS MON_NM, FAB_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '3월' AS MON_NM, MAR_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '4월' AS MON_NM, APR_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '5월' AS MON_NM, MAY_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '6월' AS MON_NM, JUN_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '7월' AS MON_NM, JUL_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '8월' AS MON_NM, AUG_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '9월' AS MON_NM, SEP_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '10월' AS MON_NM, OCT_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '11월' AS MON_NM, NOV_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '12월' AS MON_NM, DEC_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
)A
GROUP BY STATION_NM
ORDER BY TOT_CNT DESC
LIMIT 10
;






# API명세서 3번 쿼리
SELECT STATION_NM, ROUND(AVG(PSSNGR_CNT),0) AS AVG_CNT FROM (
	SELECT STATION_NM, '1월'  AS MON_NM, JAN_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '2월' AS MON_NM, FAB_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '3월' AS MON_NM, MAR_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '4월' AS MON_NM, APR_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '5월' AS MON_NM, MAY_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '6월' AS MON_NM, JUN_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '7월' AS MON_NM, JUL_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '8월' AS MON_NM, AUG_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '9월' AS MON_NM, SEP_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '10월' AS MON_NM, OCT_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '11월' AS MON_NM, NOV_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '12월' AS MON_NM, DEC_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
)A
GROUP BY STATION_NM
ORDER BY AVG_CNT
LIMIT 1
;



# API명세서 4번 쿼리
SELECT STATION_NM, MAX(PSSNGR_CNT)-MIN(PSSNGR_CNT) AS MAX_SUB_CNT FROM (
	SELECT STATION_NM, '1월'  AS MON_NM, JAN_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '2월' AS MON_NM, FAB_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '3월' AS MON_NM, MAR_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '4월' AS MON_NM, APR_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '5월' AS MON_NM, MAY_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '6월' AS MON_NM, JUN_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '7월' AS MON_NM, JUL_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '8월' AS MON_NM, AUG_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '9월' AS MON_NM, SEP_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '10월' AS MON_NM, OCT_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '11월' AS MON_NM, NOV_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
	UNION ALL
	SELECT STATION_NM, '12월' AS MON_NM, DEC_CNT AS PSSNGR_CNT FROM seoul_trft_sttn_pssngr
)A
GROUP BY STATION_NM
ORDER BY MAX_SUB_CNT DESC
LIMIT 1
;